CANVAS_WIDTH = 800
CANVAS_HEIGHT = 600 
PADDLE_WIDTH = CANVAS_WIDTH // 100 # 8
PADDLE_HEIGHT = CANVAS_WIDTH // 10 # 80
PADDLE_VELOCITY = PADDLE_HEIGHT // 16 # 10
BUFFER = PADDLE_WIDTH // 2 # Air between wall and paddle
BALL_SIZE = CANVAS_WIDTH // 200 # 4
BALL_VELOCITY = BALL_SIZE
